package ast

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/google/syzkaller/pkg/ast"
)

// AddSuffix adds a suffix to all defined names in the given syzlang spec
func AddSuffix(syzl, suffix string) (string, error) {
	// parse the syzlang spec into AST
	var parseErr error
	desc := ast.Parse([]byte(syzl), "spec.txt", func(pos ast.Pos, msg string) {
		parseErr = fmt.Errorf("syzlang syntax error at %v: %v", pos, msg)
	})
	if parseErr != nil {
		return "", parseErr
	}

	// create a mapping of original names to new names
	refs := make(map[string]string)
	for _, node := range desc.Nodes {
		name := getDefinedName(node)
		if len(name) == 0 {
			continue
		}
		switch node.(type) {
		case *ast.Resource:
			refs[name] = name + "_" + suffix
		case *ast.StrFlags:
			refs[name] = name + "_" + suffix
		case *ast.IntFlags:
			refs[name] = name + "_" + suffix
		default:
			refs[name] = formatNewName(name, suffix)
		}
	}

	// update AST nodes with new names
	for _, node := range desc.Nodes {
		updateNode(node, refs)
	}

	return string(ast.Format(desc)), nil
}

// getDefinedName returns the defined name of a syzlang node
func getDefinedName(n ast.Node) string {
	switch o := n.(type) {
	case *ast.Resource:
		return o.Name.Name
	case *ast.Call:
		return o.Name.Name
	case *ast.IntFlags:
		return o.Name.Name
	case *ast.StrFlags:
		return o.Name.Name
	case *ast.Struct:
		return o.Name.Name
	case *ast.TypeDef:
		return o.Name.Name
	}
	return ""
}

// formatNewName formats the new name by adding suffix
func formatNewName(name, suffix string) string {
	sep := "$"
	if strings.Contains(name, "$") {
		sep = "_"
	}
	return name + sep + suffix
}

// updateNode updates the names in the given AST node
func updateNode(node ast.Node, refs map[string]string) {
	// helper function to rename
	rename := func(s *string) {
		if val, ok := refs[*s]; ok {
			*s = val
		}
	}

	switch o := node.(type) {
	case *ast.Resource:
		rename(&o.Name.Name)
	case *ast.IntFlags:
		rename(&o.Name.Name)
	case *ast.StrFlags:
		rename(&o.Name.Name)
	case *ast.TypeDef:
		rename(&o.Name.Name)
		updateType(o.Type, refs)
	case *ast.Call:
		rename(&o.Name.Name)
		if o.Ret != nil {
			rename(&o.Ret.Ident)
		}
		updateFields(o.Args, refs)
	case *ast.Struct:
		rename(&o.Name.Name)
		updateFields(o.Fields, refs)
	}
}

// updateFields updates the types of fields
func updateFields(fields []*ast.Field, refs map[string]string) {
	for _, f := range fields {
		updateType(f.Type, refs)
	}
}

// updateType updates the type of a field in recursive manner
func updateType(t *ast.Type, refs map[string]string) {
	if t == nil {
		return
	}
	if val, ok := refs[t.Ident]; ok {
		t.Ident = val
	}
	for _, arg := range t.Args {
		updateType(arg, refs)
	}
}

// originally I want to record all syzlang spec info to filter redundant syscalls
// generated by agent, but some time we may want to update existing spec, that
// means new specs need to compat with existing spec. Looks SyzSpecRecord can only
// achieve filtering, but I remain it here, maybe it will be useful in the future :)
type SyzSpecRecord struct {
	Include      map[string]bool
	Resource     map[string]bool
	Define       map[string]bool
	Syscall      map[string]bool
	Flags        map[string]bool
	Struct       map[string]bool
	Union        map[string]bool
	TypeAlias    map[string]bool
	TypeTemplate map[string]bool
}

// Update update maps in SyzSpecRecord with given syzlang spec
func (ssr *SyzSpecRecord) Update(path string) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read file: %v", path)
	}
	desc := ast.Parse(b, path, func(pos ast.Pos, msg string) {
		err = fmt.Errorf("syzlang syntax error at %v: %v", pos, msg)
	})
	if err != nil {
		return err
	}
	for _, node := range desc.Nodes {
		ssr.addNode(node)
	}
	return nil
}

func (ssr *SyzSpecRecord) addNode(node ast.Node) error {
	switch o := node.(type) {
	case *ast.Resource:
		ssr.Resource[o.Name.Name] = true
	case *ast.Define:
		ssr.Define[o.Name.Name] = true
	case *ast.Call:
		ssr.Syscall[o.Name.Name] = true
	case *ast.IntFlags, *ast.StrFlags:
		// TODO: record flag's name
	case *ast.Struct:
		if o.IsUnion {
			ssr.Union[o.Name.Name] = true
		} else {
			ssr.Struct[o.Name.Name] = true
		}
	case *ast.TypeDef:
		if o.Struct != nil {
			ssr.TypeTemplate[o.Name.Name] = true
		} else {
			ssr.TypeAlias[o.Name.Name] = true
		}
	case *ast.Incdir:
	case *ast.Comment:
	case *ast.Include:
	case *ast.NewLine:
	case *ast.Meta:
	default:
		return fmt.Errorf("unknown syzlang node type: %T", node)
	}
	return nil
}

// looks only syscall field is enough?
func NewSyzSpecRecord() *SyzSpecRecord {
	return &SyzSpecRecord{
		Resource:     make(map[string]bool),
		Define:       make(map[string]bool),
		Syscall:      make(map[string]bool),
		Flags:        make(map[string]bool),
		Struct:       make(map[string]bool),
		Union:        make(map[string]bool),
		TypeAlias:    make(map[string]bool),
		TypeTemplate: make(map[string]bool),
	}
}

// ParseSyzSpec parses all .txt files in the given directory as syzlang specifications.
func Syzlang2SyzSpecRecord(dir string) (*SyzSpecRecord, error) {
	matches, err := filepath.Glob(filepath.Join(dir, "*.txt"))
	if err != nil {
		return nil, fmt.Errorf("match glob failed: %v", err)
	}
	ssr := NewSyzSpecRecord()
	for _, match := range matches {
		ssr.Update(match)
	}
	return ssr, nil
}
