package ast

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Radon10043/cloud/src/pkg/pool"
	"github.com/google/syzkaller/pkg/ast"
)

// Syznode2SpecElement converts a syzlang AST node to a SpecElement
func Syznode2SpecElement(node ast.Node) (pool.SpecElement, error) {
	d := &ast.Description{
		Nodes: []ast.Node{node},
	}
	b := ast.Format(d)
	s := strings.TrimSpace(string(b))
	switch o := node.(type) {
	case *ast.Include:
		return pool.SpecElement{
			Type: "include",
			Name: o.File.Value,
			Code: s,
		}, nil
	case *ast.Resource:
		return pool.SpecElement{
			Type: "resource",
			Name: o.Name.Name,
			Code: s,
		}, nil
	case *ast.Define:
		return pool.SpecElement{
			Type: "define",
			Name: o.Name.Name,
			Code: s,
		}, nil
	case *ast.Call:
		return pool.SpecElement{
			Type: "syscall",
			Name: o.Name.Name,
			Code: s,
		}, nil
	case *ast.IntFlags:
		return pool.SpecElement{
			Type: "flag",
			Name: o.Name.Name,
			Code: s,
		}, nil
	case *ast.StrFlags:
		return pool.SpecElement{
			Type: "flag",
			Name: o.Name.Name,
			Code: s,
		}, nil
	case *ast.Struct:
		if o.IsUnion {
			return pool.SpecElement{
				Type: "union",
				Name: o.Name.Name,
				Code: s,
			}, nil
		} else {
			return pool.SpecElement{
				Type: "struct",
				Name: o.Name.Name,
				Code: s,
			}, nil
		}
	case *ast.TypeDef:
		if o.Struct != nil {
			return pool.SpecElement{
				Type: "type-template",
				Name: o.Name.Name,
				Code: s,
			}, nil
		} else {
			return pool.SpecElement{
				Type: "type-alias",
				Name: o.Name.Name,
				Code: s,
			}, nil
		}
	case *ast.Comment, *ast.NewLine, *ast.Meta:
		return pool.SpecElement{}, nil
	default:
		return pool.SpecElement{}, fmt.Errorf("unknown syzlang node type: %T", node)
	}
}

// Syzlang2SpecPool converts a syzlang specification to a SpecPool
func Syzlang2SpecPool(spec string) (*pool.SpecPool, error) {
	// parse syzlang spec as ast
	var err error
	desc := ast.Parse([]byte(spec), "spec.txt", func(pos ast.Pos, msg string) {
		err = fmt.Errorf("syzlang syntax error at %v: %v", pos, msg)
	})
	if err != nil {
		return nil, err
	}

	// traver AST
	// NOTE: some info may be lost after conversion, e.g. comment, meta, etc.
	// But it should not be impact spec generation.
	spool := pool.NewSpecPool()
	for _, node := range desc.Nodes {
		se, err := Syznode2SpecElement(node)
		if err != nil {
			return nil, err
		}
		if se == (pool.SpecElement{}) {
			continue
		}
		spool.Insert(se)
	}
	return spool, nil
}

// originally I want to record all syzlang spec info to filter redundant syscalls
// generated by agent, but some time we may want to update existing spec, that
// means new specs need to compat with existing spec. Looks SyzSpecRecord can only
// achieve filtering, but I remain it here, maybe it will be useful in the future :)
type SyzSpecRecord struct {
	Include      map[string]bool
	Resource     map[string]bool
	Define       map[string]bool
	Syscall      map[string]bool
	Flags        map[string]bool
	Struct       map[string]bool
	Union        map[string]bool
	TypeAlias    map[string]bool
	TypeTemplate map[string]bool
}

// Update update maps in SyzSpecRecord with given syzlang spec
func (ssr *SyzSpecRecord) Update(path string) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read file: %v", path)
	}
	desc := ast.Parse(b, path, func(pos ast.Pos, msg string) {
		err = fmt.Errorf("syzlang syntax error at %v: %v", pos, msg)
	})
	if err != nil {
		return err
	}
	for _, node := range desc.Nodes {
		ssr.addNode(node)
	}
	return nil
}

func (ssr *SyzSpecRecord) addNode(node ast.Node) error {
	switch o := node.(type) {
	case *ast.Resource:
		ssr.Resource[o.Name.Name] = true
	case *ast.Define:
		ssr.Define[o.Name.Name] = true
	case *ast.Call:
		ssr.Syscall[o.Name.Name] = true
	case *ast.IntFlags, *ast.StrFlags:
		// TODO: record flag's name
	case *ast.Struct:
		if o.IsUnion {
			ssr.Union[o.Name.Name] = true
		} else {
			ssr.Struct[o.Name.Name] = true
		}
	case *ast.TypeDef:
		if o.Struct != nil {
			ssr.TypeTemplate[o.Name.Name] = true
		} else {
			ssr.TypeAlias[o.Name.Name] = true
		}
	case *ast.Incdir:
	case *ast.Comment:
	case *ast.Include:
	case *ast.NewLine:
	case *ast.Meta:
	default:
		return fmt.Errorf("unknown syzlang node type: %T", node)
	}
	return nil
}

// looks only syscall field is enough?
func NewSyzSpecRecord() *SyzSpecRecord {
	return &SyzSpecRecord{
		Resource:     make(map[string]bool),
		Define:       make(map[string]bool),
		Syscall:      make(map[string]bool),
		Flags:        make(map[string]bool),
		Struct:       make(map[string]bool),
		Union:        make(map[string]bool),
		TypeAlias:    make(map[string]bool),
		TypeTemplate: make(map[string]bool),
	}
}

// ParseSyzSpec parses all .txt files in the given directory as syzlang specifications.
func Syzlang2SyzSpecRecord(dir string) (*SyzSpecRecord, error) {
	matches, err := filepath.Glob(filepath.Join(dir, "*.txt"))
	if err != nil {
		return nil, fmt.Errorf("match glob failed: %v", err)
	}
	ssr := NewSyzSpecRecord()
	for _, match := range matches {
		ssr.Update(match)
	}
	return ssr, nil
}
