package ast

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/google/syzkaller/pkg/ast"
)

// originally I want to record all syzlang spec info to filter redundant syscalls
// generated by agent, but some time we may want to update existing spec, that
// means new specs need to compat with existing spec. Looks SyzSpecRecord can only
// achieve filtering, but I remain it here, maybe it will be useful in the future :)
type SyzSpecRecord struct {
	Include      map[string]bool
	Resource     map[string]bool
	Define       map[string]bool
	Syscall      map[string]bool
	Flags        map[string]bool
	Struct       map[string]bool
	Union        map[string]bool
	TypeAlias    map[string]bool
	TypeTemplate map[string]bool
}

// Update update maps in SyzSpecRecord with given syzlang spec
func (ssr *SyzSpecRecord) Update(path string) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read file: %v", path)
	}
	desc := ast.Parse(b, path, func(pos ast.Pos, msg string) {
		err = fmt.Errorf("syzlang syntax error at %v: %v", pos, msg)
	})
	if err != nil {
		return err
	}
	for _, node := range desc.Nodes {
		ssr.addNode(node)
	}
	return nil
}

func (ssr *SyzSpecRecord) addNode(node ast.Node) error {
	switch o := node.(type) {
	case *ast.Resource:
		ssr.Resource[o.Name.Name] = true
	case *ast.Define:
		ssr.Define[o.Name.Name] = true
	case *ast.Call:
		ssr.Syscall[o.Name.Name] = true
	case *ast.IntFlags, *ast.StrFlags:
		// TODO: record flag's name
	case *ast.Struct:
		if o.IsUnion {
			ssr.Union[o.Name.Name] = true
		} else {
			ssr.Struct[o.Name.Name] = true
		}
	case *ast.TypeDef:
		if o.Struct != nil {
			ssr.TypeTemplate[o.Name.Name] = true
		} else {
			ssr.TypeAlias[o.Name.Name] = true
		}
	case *ast.Incdir:
	case *ast.Comment:
	case *ast.Include:
	case *ast.NewLine:
	case *ast.Meta:
	default:
		return fmt.Errorf("unknown syzlang node type: %T", node)
	}
	return nil
}

// looks only syscall field is enough?
func NewSyzSpecRecord() *SyzSpecRecord {
	return &SyzSpecRecord{
		Resource:     make(map[string]bool),
		Define:       make(map[string]bool),
		Syscall:      make(map[string]bool),
		Flags:        make(map[string]bool),
		Struct:       make(map[string]bool),
		Union:        make(map[string]bool),
		TypeAlias:    make(map[string]bool),
		TypeTemplate: make(map[string]bool),
	}
}

// ParseSyzSpec parses all .txt files in the given directory as syzlang specifications.
func Syzlang2SyzSpecRecord(dir string) (*SyzSpecRecord, error) {
	matches, err := filepath.Glob(filepath.Join(dir, "*.txt"))
	if err != nil {
		return nil, fmt.Errorf("match glob failed: %v", err)
	}
	ssr := NewSyzSpecRecord()
	for _, match := range matches {
		ssr.Update(match)
	}
	return ssr, nil
}
