package tools_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/Radon10043/cloud/src/generator/agent"
	"github.com/Radon10043/cloud/src/generator/check"
	myTools "github.com/Radon10043/cloud/src/generator/tools"
	"github.com/tmc/langchaingo/llms"
)

func TestCheckSpecValidity(t *testing.T) {
	sc := check.SyzCheck{
		Bin:              filepath.Join(root, "bin", "syz-check"),
		KernelForExtract: "/vol/linux/v6.12-extract",
		KernelForCheck:   "/vol/linux/v6.12-check",
		Workdir:          filepath.Join(root, "syzkaller"),
	}
	err := sc.CheckWorkdir()
	if err != nil {
		t.Fatal(err)
	}
	toolMap := map[string]myTools.ToolExec{
		myTools.CheckSpecValidityTool.Function.Name: {
			Tool: myTools.CheckSpecValidityTool,
			Exec: myTools.ExecCheckSpecValidity,
		},
	}
	toolHelper := &myTools.ToolHelper{
		Db: nil,
		Sc: &sc,
	}
	ctx := context.Background()
	myAgent := agent.Agent{
		Ctx:        ctx,
		Model:      llm,
		Messages:   []llms.MessageContent{},
		ToolMap:    toolMap,
		ToolHelper: toolHelper,
	}
	// suppose data/test/dev_md.txt is a spec generated by agent
	specPath := filepath.Join(root, "data", "test", "dev_md.txt")
	spec, err := os.ReadFile(specPath)
	if err != nil {
		t.Fatal(err)
	}
	myAgent.AddHumanMessage(fmt.Sprintf("Please check the validity of the following syzkaller spec:\n%s", string(spec)))
	_, err = myAgent.Query()
	if err != nil {
		t.Fatal(err)
	}
	err = myAgent.ExecTools()
	if err != nil {
		t.Fatal(err)
	}
	response, err := myAgent.Query()
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("Response of agent: %v\n", response.Choices[0].Content)
}
