package tools_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/Radon10043/cloud/src/generator/check"
	myTools "github.com/Radon10043/cloud/src/generator/tools"
	"github.com/tmc/langchaingo/agents"
	"github.com/tmc/langchaingo/chains"
	"github.com/tmc/langchaingo/tools"
)

func TestCheckSpecValidity(t *testing.T) {
	sc := check.SyzCheck{
		Bin:              filepath.Join(root, "bin", "syz-check"),
		KernelForExtract: "/vol/linux/v6.12-extract",
		KernelForCheck:   "/vol/linux/v6.12-check",
		Workdir:          filepath.Join(root, "syzkaller"),
	}
	err := sc.CheckWorkdir()
	if err != nil {
		t.Fatal(err)
	}
	checkTools := []tools.Tool{
		myTools.NewCheckSpecValidityTool(&sc),
	}
	ctx := context.Background()
	agent := agents.NewOpenAIFunctionsAgent(llm, checkTools)
	executor := agents.NewExecutor(agent)
	// suppose data/test/dev_md.txt is a spec generated by agent
	specPath := filepath.Join(root, "data", "test", "dev_md.txt")
	spec, err := os.ReadFile(specPath)
	if err != nil {
		t.Fatal(err)
	}
	res, err := chains.Call(ctx, executor, map[string]interface{}{
		"input": "Please use syz-check to verify the validity of the following specifications:\n```syzlang\n" + string(spec) + "\n```",
	})
	if err != nil {
		t.Fatal(err)
	}
	fmt.Println(res["output"])
}
