FROM ubuntu:22.04

SHELL [ "/bin/bash", "-c" ]

ENV GOPATH=/usr/local/go/bin
ENV LLVM_HOME=/llvm-19
ENV PATH=$GOPATH:$LLVM_HOME/bin:$PATH
ENV TZ=Asia/Shanghai

# Install basic packages
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN apt-get install -y sudo wget curl git vim build-essential make gcc g++ flex bison bc debootstrap
RUN apt-get install -y qemu-system-x86 xz-utils cmake gdb libdw-dev libssl-dev sqlite3 libsqlite3-dev
RUN apt-get install -y rsync file devscripts equivs gnupg config-package-dev debhelper-compat dwarves
RUN apt-get install -y unzip gettext ccache git-email cpio gawk lsb-release software-properties-common
RUN apt-get install -y cloc openssh-server python3 python3-pip python3-dev language-pack-en-base jq
RUN apt-get install -y pkg-config libzstd-dev libxml2-dev zlib1g-dev

RUN apt-get install -y bmake libarchive-tools libbsd-dev time libarchive-dev libarchive-tools libncurses5-dev

RUN apt-get install -y gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu gcc-mips64el-linux-gnuabi64
RUN apt-get install -y gcc-powerpc64le-linux-gnu gcc-riscv64-linux-gnu gcc-s390x-linux-gnu

# Install LLVM-19
RUN wget https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz
RUN mkdir /llvm-19 && tar -C /llvm-19 -xvf LLVM-19.1.7-Linux-X64.tar.xz --strip-components=1
RUN rm LLVM-19.1.7-Linux-X64.tar.xz

# Install golang-1.23.6
RUN wget https://go.dev/dl/go1.23.6.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.23.6.linux-amd64.tar.gz && \
    rm go1.23.6.linux-amd64.tar.gz

# Install flatbuffers-2.0.8
RUN wget https://github.com/google/flatbuffers/archive/refs/tags/v2.0.8.tar.gz
RUN tar -xzvf v2.0.8.tar.gz && \
    pushd flatbuffers-2.0.8 && \
    cmake -G "Unix Makefiles" && \
    make -j && \
    make install && \
    popd && \
    rm -rf v2.0.8.tar.gz flatbuffers-2.0.8
