package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Radon10043/cloud/src/pkg/ast"
)

var (
	flagIndir  string
	flagOutdir string
)

func main() {
	// parse command line flags
	flag.StringVar(&flagIndir, "indir", "", "path to spec dir generated by cloud")
	flag.StringVar(&flagOutdir, "outdir", "", "Path to the output directory")
	flag.Parse()

	// validate flags
	if flagIndir == "" {
		panic("suffix flag is required")
	}
	if flagOutdir == "" {
		panic("file flag is required")
	}

	var err error
	if flagIndir, err = filepath.Abs(flagIndir); err != nil {
		panic(err)
	}
	if flagOutdir, err = filepath.Abs(flagOutdir); err != nil {
		panic(err)
	}
	if err = os.MkdirAll(flagOutdir, 0755); err != nil {
		panic(err)
	}

	files, err := filepath.Glob(
		filepath.Join(flagIndir, "*", "spec#comp.txt"),
	)
	if err != nil {
		panic(err)
	}
	for _, file := range files {
		dname := filepath.Base(filepath.Dir(file))
		seq := strings.Split(dname, "#")
		if len(seq) < 2 {
			panic("not spec file generated by cloud")
		}
		vname, mname := seq[0], seq[1]

		// read the input syzlang spec file
		b, err := os.ReadFile(file)
		if err != nil {
			panic(err)
		}
		syzl := string(b)

		// add suffix to defined names in the syzlang spec
		nsyzl, err := ast.AddSuffix(syzl, vname)
		if err != nil {
			fmt.Printf("refactor %s failed, reuse old one.\n", file)
			nsyzl = syzl
		}

		// write new spec to the output directory
		fname := fmt.Sprintf("cloud#%s#%s.txt", vname, mname)
		fpath := filepath.Join(flagOutdir, fname)
		os.WriteFile(fpath, []byte(nsyzl), 0755)
	}
	fmt.Printf("done.\n")
}
