package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Radon10043/cloud/src/pkg/ast"
	"github.com/Radon10043/cloud/src/pkg/pool"
)

var (
	flagIndir  string
	flagOutdir string
)

func main() {
	// parse command line flags
	flag.StringVar(&flagIndir, "indir", "", "path to \"specs\" dir generated by cloud")
	flag.StringVar(&flagOutdir, "outdir", "", "Path to the output directory")
	flag.Parse()

	// validate flags
	if flagIndir == "" {
		panic("-indir is required")
	}
	if flagOutdir == "" {
		panic("-outdir is required")
	}

	var (
		err    error
		indir  string
		outdir string
	)
	if indir, err = filepath.Abs(flagIndir); err != nil {
		panic(err)
	}
	if outdir, err = filepath.Abs(flagOutdir); err != nil {
		panic(err)
	}
	if err = os.MkdirAll(outdir, 0755); err != nil {
		panic(err)
	}

	files, err := filepath.Glob(
		filepath.Join(indir, "*", "spec#comp.txt"),
	)
	if err != nil {
		panic(err)
	}
	for _, file := range files {
		dname := filepath.Base(filepath.Dir(file))
		seq := strings.Split(dname, "#")
		if len(seq) < 2 {
			panic("not spec file generated by cloud")
		}
		vname, mname := seq[0], seq[1]

		poolFile := filepath.Join(filepath.Dir(file), ".pool")
		poolByte, err := os.ReadFile(poolFile)
		dotpool, err := pool.NewSpecPoolFromJson(string(poolByte))
		if err != nil {
			panic(err)
		}
		if len(*dotpool) == 0 {
			fmt.Printf("[%s] corresponding .pool is empty, skip refactoring.\n", vname)
			continue
		}

		// read the input syzlang spec file
		b, err := os.ReadFile(file)
		if err != nil {
			panic(err)
		}
		syzl := string(b)

		// add suffix to defined names in the syzlang spec
		nsyzl, err := ast.AddSuffix(syzl, vname)
		if err != nil {
			fmt.Printf("[%s] refactor failed, reuse old one.\n", vname)
			nsyzl = syzl
		}

		// write new spec to the output directory
		fname := fmt.Sprintf("cloud#%s#%s.txt", vname, mname)
		fpath := filepath.Join(outdir, fname)
		os.WriteFile(fpath, []byte(nsyzl), 0755)
	}
	fmt.Printf("done.\n")
}
