#!/bin/bash

# this script is used to reproduce bugs from log files generated by syzkaller
#
# usage:
#   bash scripts/repro.sh
#
# kill all repro jobs:
#   pkill repro.sh; pkill syz-repro

set -euo pipefail

# required args
REPRO_SH_CONFIG_PATH=

# optional args
JOBS=8 # number of parallel jobs

# function to print help message
print_help() {
    echo "usage: $0 [ARGS]"
    echo "  args (required):"
    echo "    -c, --config <CONFIG> path to the config file for repro.sh, see configs/repro/reprosh.cfg for reference"
    echo "  args (optional):"
    echo "    -j, --jobs            number of parallel reproduce jobs (default: 8)"
    echo "    -h, --help            print help message"
}

while [[ $# -gt 0 ]]; do
    case $1 in
    -c | --config)
        REPRO_SH_CONFIG_PATH=$2
        shift
        shift
        ;;
    -j | --jobs)
        JOBS=$2
        shift
        shift
        ;;
    -h | --help)
        print_help
        exit 0
        ;;
    *)
        echo "unknown arg: $1"
        exit 1
        ;;
    esac
done

# reproduce bugs in parallel
mapfile -t LOGS < <(jq -r .logs[] $REPRO_SH_CONFIG_PATH)
for LOG in "${LOGS[@]}"; do

    REPRO_JOBS=$(pgrep -c syz-repro || true)
    while [ $REPRO_JOBS -ge $JOBS ]; do
        sleep 1m
        REPRO_JOBS=$(pgrep -c syz-repro || true)
    done

    LOG_NAME=$(basename $LOG)
    LOG_DIR=$(dirname $LOG)
    LOG_HASH=$(basename $LOG_DIR)

    echo "reproducing $LOG ..."
    WORKDIR=$(dirname $(dirname $LOG_DIR))/repro/$LOG_HASH/$LOG_NAME
    SYZKALLER_CONFIG_PATH=$(jq -r .config $REPRO_SH_CONFIG_PATH)
    SYZKALLER=$(jq -r .syzkaller $SYZKALLER_CONFIG_PATH)
    mkdir -p $WORKDIR
    jq ".vm.count = 1" $SYZKALLER_CONFIG_PATH >$WORKDIR/repro.cfg
    nohup $SYZKALLER/bin/syz-repro \
        -config=$WORKDIR/repro.cfg \
        -output=$WORKDIR/repro.syz \
        -crepro=$WORKDIR/repro.c $LOG >$WORKDIR/repro.log 2>&1 &

done

# waiting for the remaining repro tasks to finish
while [ $REPRO_JOBS -gt 0 ]; do
    sleep 30s
    REPRO_JOBS=$(pgrep -c syz-repro || true)
done
echo "all repro tasks done!"