#!/bin/bash

# this scripts is written for tidying spec files from specs directory,
# which are generated by cloud.
#
# usage:
#  bash scripts/spec-tidy.sh -i <SPEC_DIR> -o <OUT_DIR>

set -euo pipefail

# required args
SPEC_DIR=
OUT_DIR=

print_help() {
    echo "usage: $0 [ARGS]"
    echo "  args (required):"
    echo "    -i, --input <SPEC_DIR>    path to the directory containing spec files to be tidied"
    echo "    -o, --output <OUT_DIR>    path to the directory where the tidied spec files will be saved"
    echo "  args (optional):"
    echo "    -h, --help                print help message"
}

while [[ $# -gt 0 ]]; do
    case $1 in
    -i | --input)
        SPEC_DIR=$(realpath $2)
        shift
        shift
        ;;
    -o | --output)
        OUT_DIR=$(realpath $2)
        shift
        shift
        ;;
    -h | --help)
        print_help
        exit 0
        ;;
    *)
        echo "unknown arg: $1"
        exit 1
        ;;
    esac
done

if [[ -z "$SPEC_DIR" ]] || [[ -z "$OUT_DIR" ]]; then
    echo "Error: Missing required arguments."
    print_help
    exit 1
fi

mkdir -p $OUT_DIR
for f in $(find $SPEC_DIR -type f -name "spec#comp.txt"); do
    var=$(basename $(dirname $f) | cut -d# -f1)
    llm=$(basename $(dirname $f) | cut -d# -f2)
    outf=$OUT_DIR/cloud\#$var\#$llm.txt
    echo "$f -> $outf"
    cp $f $outf
done
echo "Done!"
